// <auto-generated />
using System;
using FiapCloudGames.Games.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FiapCloudGames.Games.Infrastructure.Migrations
{
    [DbContext(typeof(FiapCloudGamesGamesDbContext))]
    [Migration("20251004020753_FixNullableColumn")]
    partial class FixNullableColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FiapCloudGames.Games.Domain.Entities.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameId"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("GameId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("FiapCloudGames.Games.Domain.Entities.GameGenre", b =>
                {
                    b.Property<int>("GameGenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameGenreId"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("GameGenreId");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("GameGenres");

                    b.HasData(
                        new
                        {
                            GameGenreId = 1,
                            Title = "Action"
                        },
                        new
                        {
                            GameGenreId = 2,
                            Title = "Adventure"
                        },
                        new
                        {
                            GameGenreId = 3,
                            Title = "Simulation"
                        },
                        new
                        {
                            GameGenreId = 4,
                            Title = "Strategy"
                        },
                        new
                        {
                            GameGenreId = 5,
                            Title = "Sports"
                        },
                        new
                        {
                            GameGenreId = 6,
                            Title = "Racing"
                        },
                        new
                        {
                            GameGenreId = 7,
                            Title = "Fight"
                        },
                        new
                        {
                            GameGenreId = 8,
                            Title = "Shooter"
                        },
                        new
                        {
                            GameGenreId = 9,
                            Title = "Platformer"
                        },
                        new
                        {
                            GameGenreId = 10,
                            Title = "Puzzle"
                        },
                        new
                        {
                            GameGenreId = 11,
                            Title = "Horror"
                        },
                        new
                        {
                            GameGenreId = 12,
                            Title = "Stealth"
                        },
                        new
                        {
                            GameGenreId = 13,
                            Title = "Sandbox"
                        },
                        new
                        {
                            GameGenreId = 14,
                            Title = "MMORPG"
                        },
                        new
                        {
                            GameGenreId = 15,
                            Title = "BattleRoyale"
                        },
                        new
                        {
                            GameGenreId = 16,
                            Title = "MusicRhythm"
                        },
                        new
                        {
                            GameGenreId = 17,
                            Title = "Indie"
                        });
                });

            modelBuilder.Entity("FiapCloudGames.Games.Domain.Entities.Purchase", b =>
                {
                    b.Property<int>("PurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurchaseId"));

                    b.Property<DateTime>("OrderedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PurchaseId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("GameGameGenre", b =>
                {
                    b.Property<int>("GamesGameId")
                        .HasColumnType("int");

                    b.Property<int>("GenresGameGenreId")
                        .HasColumnType("int");

                    b.HasKey("GamesGameId", "GenresGameGenreId");

                    b.HasIndex("GenresGameGenreId");

                    b.ToTable("GameGameGenre");
                });

            modelBuilder.Entity("GamesPurchases", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("PurchaseId")
                        .HasColumnType("int");

                    b.HasKey("GameId", "PurchaseId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("GamesPurchases");
                });

            modelBuilder.Entity("GameGameGenre", b =>
                {
                    b.HasOne("FiapCloudGames.Games.Domain.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FiapCloudGames.Games.Domain.Entities.GameGenre", null)
                        .WithMany()
                        .HasForeignKey("GenresGameGenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GamesPurchases", b =>
                {
                    b.HasOne("FiapCloudGames.Games.Domain.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FiapCloudGames.Games.Domain.Entities.Purchase", null)
                        .WithMany()
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
